apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ymxx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-ymxx@sha256:b9f4a2201b2f32d44e86418489cbd5bfb0b731365280c5133c779a096d3a9e1e
        name: my-nodejs
        resources: {}
status: {}
